
// Get User by id
GET http://localhost:8080/getUserById/123
Content-Type: application/json

### 

POST http://localhost:8080/createUser
Content-Type: application/application/json

{
  "email":"fernelladev@gmail.com",
  "password":"123456#D",
  "name":"Fernella",
  "age": 25
}

### 